USE [master]
GO

/****** Object:  Database [Мирвелов 4312 БД]    Script Date: 08.12.2021 15:52:29 ******/
CREATE DATABASE [Мирвелов 4312 БД] ON  PRIMARY 
( NAME = N'Мирвелов 4312 БД', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Мирвелов 4312 БД.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Мирвелов 4312 БД_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Мирвелов 4312 БД_log.ldf' , SIZE = 9216KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Мирвелов 4312 БД].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Мирвелов 4312 БД] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET ARITHABORT OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET RECOVERY FULL 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET  MULTI_USER 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Мирвелов 4312 БД] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Мирвелов 4312 БД] SET  READ_WRITE 
GO

